// Code generated by protoc-gen-go.
// source: users.proto
// DO NOT EDIT!

/*
Package Users is a generated protocol buffer package.

It is generated from these files:
	users.proto

It has these top-level messages:
	User
	UserRequest
	UserReply
*/
package Users

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type User struct {
	SocialID  string `protobuf:"bytes,1,opt,name=SocialID,json=socialID" json:"SocialID,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=Email,json=email" json:"Email,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=FirstName,json=firstName" json:"FirstName,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=Name,json=name" json:"Name,omitempty"`
	LastLogin int64  `protobuf:"varint,5,opt,name=LastLogin,json=lastLogin" json:"LastLogin,omitempty"`
	Balance   int64  `protobuf:"varint,6,opt,name=Balance,json=balance" json:"Balance,omitempty"`
	Referrer  string `protobuf:"bytes,7,opt,name=Referrer,json=referrer" json:"Referrer,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetSocialID() string {
	if m != nil {
		return m.SocialID
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetLastLogin() int64 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

func (m *User) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *User) GetReferrer() string {
	if m != nil {
		return m.Referrer
	}
	return ""
}

// The request message containing the user's name.
type UserRequest struct {
	User *User `protobuf:"bytes,1,opt,name=User,json=user" json:"User,omitempty"`
}

func (m *UserRequest) Reset()                    { *m = UserRequest{} }
func (m *UserRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()               {}
func (*UserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// The response message containing the greetings
type UserReply struct {
	User *User `protobuf:"bytes,1,opt,name=User,json=user" json:"User,omitempty"`
}

func (m *UserReply) Reset()                    { *m = UserReply{} }
func (m *UserReply) String() string            { return proto.CompactTextString(m) }
func (*UserReply) ProtoMessage()               {}
func (*UserReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "Users.User")
	proto.RegisterType((*UserRequest)(nil), "Users.UserRequest")
	proto.RegisterType((*UserReply)(nil), "Users.UserReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Users service

type UsersClient interface {
	// Sends a greeting
	UpdateUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserReply, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) UpdateUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserReply, error) {
	out := new(UserReply)
	err := grpc.Invoke(ctx, "/Users.Users/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersServer interface {
	// Sends a greeting
	UpdateUser(context.Context, *UserRequest) (*UserReply, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users.Users/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Users.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateUser",
			Handler:    _Users_UpdateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}

func init() { proto.RegisterFile("users.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x50, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x75, 0x6d, 0xb6, 0xdb, 0xcc, 0x5e, 0x64, 0xf0, 0x10, 0x4a, 0xc1, 0xb2, 0xa7, 0x1e, 0x64,
	0x0f, 0xd5, 0xab, 0x17, 0x51, 0x41, 0x28, 0x1e, 0x22, 0xfd, 0x01, 0x69, 0x9d, 0xca, 0x42, 0xba,
	0x1b, 0x93, 0xf4, 0xd0, 0x3f, 0xe7, 0x6f, 0x93, 0x4c, 0x5a, 0xd0, 0x93, 0x97, 0x90, 0xf7, 0x01,
	0xf3, 0xde, 0x83, 0xfa, 0x10, 0xc8, 0x87, 0xd6, 0xf9, 0x21, 0x0e, 0x58, 0xae, 0x13, 0x68, 0xbe,
	0x0b, 0x10, 0xe9, 0x87, 0x53, 0x98, 0xbc, 0x0f, 0xdb, 0xce, 0xd8, 0xd7, 0x27, 0x55, 0xcc, 0x8b,
	0x85, 0xd4, 0x93, 0x70, 0xc2, 0x78, 0x0d, 0xe5, 0xf3, 0xde, 0x74, 0x56, 0x5d, 0xb2, 0x50, 0x52,
	0x02, 0x38, 0x03, 0xf9, 0xd2, 0xf9, 0x10, 0xdf, 0xcc, 0x9e, 0xd4, 0x88, 0x15, 0xb9, 0x3b, 0x13,
	0x88, 0x20, 0x58, 0x10, 0x2c, 0x88, 0x3e, 0x71, 0x33, 0x90, 0x2b, 0x13, 0xe2, 0x6a, 0xf8, 0xec,
	0x7a, 0x55, 0xce, 0x8b, 0xc5, 0x48, 0x4b, 0x7b, 0x26, 0x50, 0x41, 0xf5, 0x68, 0xac, 0xe9, 0xb7,
	0xa4, 0xc6, 0xac, 0x55, 0x9b, 0x0c, 0x53, 0x36, 0x4d, 0x3b, 0xf2, 0x9e, 0xbc, 0xaa, 0x72, 0x36,
	0x7f, 0xc2, 0x4d, 0x0b, 0x75, 0xca, 0xaf, 0xe9, 0xeb, 0x40, 0x21, 0xe2, 0x4d, 0xae, 0xc3, 0x15,
	0xea, 0x65, 0xdd, 0x72, 0x4b, 0x7e, 0xb5, 0x48, 0xf5, 0x9b, 0x5b, 0x90, 0xd9, 0xef, 0xec, 0xf1,
	0x5f, 0xf7, 0xf2, 0x01, 0xf2, 0x4e, 0x78, 0x0f, 0xb0, 0x76, 0x1f, 0x26, 0x12, 0x8f, 0x85, 0xbf,
	0x9d, 0xf9, 0xf2, 0xf4, 0xea, 0x0f, 0xe7, 0xec, 0xb1, 0xb9, 0xd8, 0x8c, 0x79, 0xeb, 0xbb, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x82, 0x12, 0xd7, 0x7a, 0x01, 0x00, 0x00,
}
