// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

/*
Package User is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	User
*/
package User

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type User struct {
	SocialID  string `protobuf:"bytes,1,opt,name=SocialID,json=socialID" json:"SocialID,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=Email,json=email" json:"Email,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=FirstName,json=firstName" json:"FirstName,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=Name,json=name" json:"Name,omitempty"`
	LastLogin int64  `protobuf:"varint,5,opt,name=LastLogin,json=lastLogin" json:"LastLogin,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetSocialID() string {
	if m != nil {
		return m.SocialID
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetLastLogin() int64 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "User.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x09, 0x2d, 0x4e, 0x2d, 0x52, 0xea, 0x60, 0xe4,
	0x02, 0x33, 0x84, 0xa4, 0xb8, 0x38, 0x82, 0xf3, 0x93, 0x33, 0x13, 0x73, 0x3c, 0x5d, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x38, 0x8a, 0xa1, 0x7c, 0x21, 0x11, 0x2e, 0x56, 0xd7, 0xdc, 0xc4,
	0xcc, 0x1c, 0x09, 0x26, 0xb0, 0x04, 0x6b, 0x2a, 0x88, 0x23, 0x24, 0xc3, 0xc5, 0xe9, 0x96, 0x59,
	0x54, 0x5c, 0xe2, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0x0c, 0x96, 0xe1, 0x4c, 0x83, 0x09, 0x08, 0x09,
	0x71, 0xb1, 0x80, 0x25, 0x58, 0xc0, 0x12, 0x2c, 0x79, 0x20, 0x31, 0x19, 0x2e, 0x4e, 0x9f, 0xc4,
	0xe2, 0x12, 0x9f, 0xfc, 0xf4, 0xcc, 0x3c, 0x09, 0x56, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0xce, 0x1c,
	0x98, 0x40, 0x12, 0x1b, 0xd8, 0x5d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x04, 0x74,
	0x9b, 0xa5, 0x00, 0x00, 0x00,
}
